# -*- coding: utf-8 -*-
"""LightGBM.ipynb

Automatically generated by Colab.

Original file is located at
    Google Colab
"""

import lightgbm as lgb
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer, fetch_california_housing
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import train_test_split
import joblib

data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)

X

y = data.target
y

import warnings
warnings.filterwarnings('ignore')

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

train_data = lgb.Dataset(x_train, label=y_train)

test_data = lgb.Dataset(x_test, label=y_test)

params = {
    "objective" : "binary",
    "metric" : "binary_error",
    "boosting_type": "gbdt",
    "learning_rate" : 0.1,
    "verbose" : -1
    }

model_classification = lgb.train(
    params, train_data, valid_sets=[test_data], num_boost_round=100
)

y_pred = model_classification.predict(x_test)
y_pred

y_pred_binary = [1 if p >= 0.5 else 0 for p in y_pred]

y_pred_binary

accuracy_score(y_test, y_pred_binary)

housing = fetch_california_housing()

x = pd.DataFrame(housing.data, columns=housing.feature_names)

x

y = housing.target

y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

train_data = lgb.Dataset(x_train, label=y_train)

test_data = lgb.Dataset(x_test, label=y_test)

params = {
    "objective" : "regression",
    "metric" : "rmse",
    "boosting_type": "gbdt",
    "learning_rate" : 0.05,
    "num_leaves" : 30,
    "verbose" : -1
    }

model_regression = lgb.train(params, train_data, valid_sets=[test_data], num_boost_round=500)

y_pred = model_regression.predict(x_test)

print(np.sqrt(mean_squared_error(y_test, y_pred)))

joblib.dump(model_classification, "lightgbm_classification.pkl")

joblib.dump(model_regression, "lightgbm_regression.pkl")