# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    Google Colab
"""

import numpy as np

"""# **The Basics**

"""

a = np.array([1, 2, 3])
print(a)

b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

# Get Dimension
b.ndim

# Get Shape
print(a.shape) # Gets Rows and Columns If not then not showing anything
print(b.shape)

# Get Type
print(a.dtype)
print(b.dtype)

c = np.array([1, 2, 3], dtype="int16")
print(c.dtype)

# Get Size
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

# Get Total Size
print(a.size * a.itemsize)
print(a.nbytes)

"""# Accessing/Changing Specific elements, rows, columns etc."""

a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
print(a.shape)

# Get a Specific elements [r, c]
print(a[1, 5]) # Accessing 13
print(a[1, -2]) # Accessing 13

# Get a Specific Row
print(a[0, :])
# Get a Specific Column
print(a[:, 0])

# Getting a little bit fancy [startIndex:endIndex:stepSize]
# Getting Number 2 - 6
print(a[0, 1:-1])
print(a[0, 1:6:2])

# Changing Specific Elements
a[1, 5] = 20
print(a)
a[:,2] = [1,2]
print(a)

# 3D Example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

# Get Specific Elements (Work Outside In)
print(b[0][1][1]) # Selecteng 4

# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)
# b[:, 1, :] = [[9, 9, 9], [8, 8]] # Will Get Error
# print(b)

"""# Initializing Different Types Of Arrays"""

# All 0s Matrix
np.zeros((2))
np.zeros((2, 3))
# np.zeros((2, 3, 3))
# np.zeros((2, 3, 3, 2))

# All 1s Matrix
np.ones((4, 2, 2), dtype="int32")

# Any Other Number
np.full((2, 2), 99)

# Any other number (Full like)
np.full_like(a, 4)
np.full(a.shape, 4)

# Random decimal numbers
np.random.rand(4, 2)
np.random.random_sample(a.shape)

# Random Integer Values
np.random.randint(2, 7, size=(3, 3))

np.identity(5)

# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

"""**Problem #1 (How do you initialize this array?)**"""

arr = np.ones((5, 5), dtype="int32")
arr[1:-1,1:-1] = 0
arr[2, 2] = 9
print(arr)

"""Be Careful when coping arrays

"""

a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)


# So WE need to do
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

"""# Mathematics"""

a = np.array([1,2,3,4])
print(a)

a + 2

a - 3

a * 2

a / 2

a -= 2

b = np.array([1,0,1,0])
a + b

a ** 2

# Take The Sin, cos, tan
np.sin(a)
np.cos(a)
np.tan(a)

# More About Math
# https://numpy.org/doc/stable/reference/routines.math.html

"""**Linear Algebra**"""

a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

# Find The Ditermiant
c = np.identity(3)
np.linalg.det(c)

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

"""**Statistics**"""

stats = np.array([[1,2,3], [4,5,6]])
stats

np.min(stats)
np.min(stats, axis=1)

np.max(stats)

np.sum(stats)

"""# Reorganizing Arrays"""

before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

# Horizontal Stack
h1 = np.ones((2,4), dtype="int32")
h2 = np.zeros((2,2), dtype="int32")

np.hstack((h1, h2))

"""# Load Data From File"""

# !touch data.txt
# !printf "1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5\n3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12\n1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88\n" > data.txt

filedata = np.genfromtxt("data.txt", delimiter=",")
filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

"""# Advanced Indexing and Boolean Masking

"""

filedata > 50

filedata[filedata > 50]

# You Can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1, 2, 8]]

np.any(filedata > 50, axis=0)

((filedata > 50) & (filedata < 100))
filedata[((filedata > 50) & (filedata < 100))]

(~((filedata > 50) & (filedata < 100)))

"""# Problem #2 (How do you index these values?)"""

# !printf "1,2,3,4,5\n6,7,8,9,10\n11,12,13,14,15\n16,17,18,19,20\n21,22,23,24,25\n26,27,28,29,30\n" > data.txt

question_data = np.genfromtxt("data.txt", delimiter=",")
question_data = question_data.astype('int32')
question_data

# How to Index 11 12 16 17
question_data[2:-2, :2]
print(question_data[2:-2, :2])

# How To Index 2 8 14 20
for i in range(1,5):
  print(question_data[i-1:i, i:i+1])

question_data[[0, 1, 2, 3], [1,2,3,4]]

# How to Index 4 5 then 24 25 29 30
question_data[[0, 4, 5], 3:]